services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db-development
      - db-test
  db-development:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_development:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: db_development
  db-test:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_test:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: db_test
volumes:
  db_development:
  db_test:

