FROM ruby:3.2

RUN apt-get update -qq && \
  apt-get install -y nodejs postgresql-client

WORKDIR /rails

COPY Gemfile /rails/Gemfile
COPY Gemfile.lock /rails/Gemfile.lock

RUN bundle install

EXPOSE 3000

# CMD ["bash", "-c", "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"]
CMD ["bash", "-c", "bin/rails s -p 3000 -b '0.0.0.0'"]
